### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by jiahao** [EconForge/NLsolve.jl#38]
In particular, the current release version is unusable (fixed in f4f1785cf2873c4193fc61dcf2c1cde9654f237a)

**Comment by KristofferC** [comment]
Unless anyone gets to it before me I will do it today.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4523

**Comment by KristofferC** [comment]
Also, the current release of NLsolve works fine on julia release, as well as the current master of NLsolve works fine on julia master. If you want to use julia master you should expect to use `Pkg.checkout`

Calling the current release version *unusable* because it doesn't work with the very latest commits to julia master comes of as rude.

**Comment by spencerlyon2** [comment]
Thanks for taking care of this @KristofferC

**Comment by jiahao** [comment]
Sorry if that came across as stern. Doing a `Pkg.add` on a clean copy of Julia master installed a version of the code that had the itinerant subscript `k`.
